### ISSUE TITLE
Path to binary not taken into account

### ISSUE THREAD

**Issue by jeanrjc** [sieren/QSyncthingTray#8]
On OSX 10.8.5, an QsyncthingTray from QsyncthingTray.dmg release 0.1.1.

It works if syncthing is already on, but do not if syncthing is off and after filling the path which is not saved between sessions (After quitting and reopening).

**Comment by sieren** [comment]
Thanks for the report. I will look into this.

**Comment by sieren** [comment]
@jeanrjc were you able to reproduce it with version 0.2 ? (Up in releases)

**Comment by jeanrjc** [comment]
Can you provide a dmg version ? I don't have Xcode nor Qt.

**Comment by sieren** [comment]
Sorry, just noticed the recent one didnt have a DMG attached. I just published a new one:
https://github.com/sieren/QSyncthingTray/releases/tag/v0.2.1

**Comment by jeanrjc** [comment]
Thanks for the dmg, but the issue remains. It would be nice to have a button to validate or something to say that QST took the path into account.

Thanks

**Comment by sieren** [comment]
Oh, hold on. Actually you need to select the binary, not just the path - maybe thats the issue?
(Either way, I probably need to add error handling or be more specific in the next update)

**Comment by jeanrjc** [comment]
Yes, I specify the path to the binary, eg:

    ~/Library/syncthing-macosx-amd64-v0.11.9/syncthing

But the problem is that when I quit and re-open, nothing is in the Path field.

**Comment by sieren** [comment]
Interesting. Guess I will need to setup a 10.8 machine and track this issue as I cant reproduce it on 10.10..

**Comment by jeanrjc** [comment]
Ok, the issue is when I specify the path by hand, because it works if I use the `Browse` button. The problem is then if the binary can't be access with the `Browse` button (as in my example). The solution is to move it to a visible folder, eg:

    ~/Documents/syncthing-macosx-amd64-v0.11.9/syncthing

Thanks

**Comment by sieren** [comment]
Ah, i see. Thanks for the details, I'll look into how to handle that (as a workaround you can use CMD+SHIFT+G in the Browse window and specify the otherwise hidden Library path there).

**Comment by jeanrjc** [comment]
Ah, thanks for the workaround.

**Comment by sieren** [comment]
Fixed in https://github.com/sieren/QSyncthingTray/pull/10
